book_title: Way of choices
links:
    prefix_url: ""
    source_url: https://novelbin.org/novelbin/ze-tian-ji/chapter-1
identifiers:
    next_chapter:
        tag: a
        type: id
        name: next_chap
    content: 
        tag: div
        type: class_
        name: chap-c
    title:
        tag: a
        type: class_
        name: chr-title
        attribute: title
text_filter:
    - Ads by PubFuture
    - Reddit
    - Facebook
    - Chapter end
    - Report
