book_title: Martial world
links:
    prefix_url: https://readnovelfull.me
    source_url: https://readnovelfull.me/martial-world/chapter-0-magic-cube/
identifiers:
    next_chapter:
        tag: a
        type: id
        name: next_chap
    content: 
        tag: div
        type: class_
        name: chap-c
    title:
        tag: a
        type: class_
        name: chr-title
        attribute: title
text_filter:
    - Ads by PubFuture
    - Reddit
    - Facebook
    - Chapter end
    - Report
