book_title: A will eternal
links:
    prefix_url: https://readnovelfull.me
    source_url: https://readnovelfull.me/a-will-eternal/chapter-1-im-bai-xiaochun/
identifiers:
    next_chapter:
        tag: a
        type: id
        name: next_chap
    content: 
        tag: div
        type: class_
        name: chr-c
    title:
        tag: a
        type: class_
        name: chr-title
        attribute: title
text_filter:
    - Ads by PubFuture
    - Reddit
    - Facebook
    - Chapter end
    - Report
